### PR TITLE
Prelimenary Battle Class

### PR DESCRIPTION
**Pull request by andrew-pa**
This PR includes a preliminary pre-spec Battle class. It also fixes the inventory switch block so that it doesn't fall through the cases. Also I added some of my thoughts to the README.

### CODE REVIEW

**Comment by Virepri** [comment]
Gonna pull it in-- when the spec comes, I'll work on that

**Comment by andrew-pa** [comment]
Kool

**Comment by andrew-pa** [comment]
We'll both probably have a lot of refining to do when the real specs are published

**Comment by Virepri** [comment]
True-- I'm also planning to drop on a UI- plelerson is OK with it

**Pull request merged**
