### PR TITLE
Battle class up-to-spec

### PR DESCRIPTION
**Pull request by andrew-pa**
This is pretty much up to spec, although I would go over it to be sure. 

Two things I noticed:
* The spec example says '@playerName@ gets a critical hit!' before printing the amount of damage done when the enemy is defeated
* Our inventory is not the same as the spec's example's inventory

Also might want to change the enemy names / min+max damage

### CODE REVIEW

**Comment by andrew-pa** [comment]
Also I left the welcome message and didn't put the min/max damage in the toString description, which may be necessary although the spec example doesn't seem to print descriptions at all

**Comment by andrew-pa** [comment]
Also do we know if the specs for the other pieces have changed?

**Comment by Virepri** [comment]
Nope, no changes. Pulling in now, I'll be home in an hour or too

**Comment by Virepri** [comment]
I'll do enemy name generation when I get home

**Comment by andrew-pa** [comment]
Kool. See if you can make similarly named enemies have similar min/max damages + healths

**Comment by Virepri** [comment]
That's fairly easy-- I'll make a set of names and such. I'm also considering having freeze & fire effects, freeze being your attack being temporarily reduced, fire being that you take more damage without armor equipped

**Comment by andrew-pa** [comment]
If you closely follow the spec then others can reuse without it being obvious






On Thu, Dec 3, 2015 at 4:18 PM -0800, "Virepri" <notifications@github.com> wrote:





That's fairly easy-- I'll make a set of names and such. I'm also considering having freeze & fire effects, freeze being your attack being temporarily reduced, fire being that you take more damage without armor equipped

---

**Comment by Virepri** [comment]
I'm talking about just forking it and doing my stuff there

**Comment by Virepri** [comment]
Anyway, headed home now

**Pull request merged**
